# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_widget = QtWidgets.QWidget(self.centralwidget)
        self.bg_widget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.bg_widget.setStyleSheet("QWidget#bg_widget {\n"
"background-image: url(/Users/rosemusalli/Desktop/pyqt5_project/assets/bg3.jpeg);\n"
"background-position: center;\n"
"background-size: cover;\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.main_widget = QtWidgets.QWidget(self.bg_widget)
        self.main_widget.setGeometry(QtCore.QRect(120, 100, 531, 331))
        self.main_widget.setStyleSheet("QWidget#main_widget{\n"
"background-color: rgba(0, 0, 0, 222);\n"
"}\n"
"")
        self.main_widget.setObjectName("main_widget")
        self.title = QtWidgets.QLabel(self.main_widget)
        self.title.setGeometry(QtCore.QRect(0, 30, 531, 71))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 40pt \"Times New Roman\";\n"
"qproperty-alignment: \'AlignCenter\';")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.main_widget)
        self.label.setGeometry(QtCore.QRect(30, 90, 481, 121))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 16pt \"Times New Roman\";\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.main_widget)
        self.pushButton.setGeometry(QtCore.QRect(200, 240, 141, 51))
        self.pushButton.setStyleSheet("border-radius: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Helvetica Neue\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Fetal Vision"))
        self.label.setText(_translate("MainWindow", "An AI-powered tool for sonologists that uses deep learning to segment and measure key fetal biometric parameters from 2D ultrasound images, enhancing prenatal diagnostics and care efficiency."))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
